### ISSUE TITLE
Understanding the outcomes of Google Summer of Code

### ISSUE THREAD

**Issue by j3ffsilva** [fandango-/spad#1]
Dear Abhinav Baid,

I am a Ph.D. student at the University of São Paulo (Brazil). We would like to understand how and how much Open Source Communities benefit from participating in Google Summer of Code (GSoC). We believe that your experience in GSoC is valuable and could help us achieve that. In a 1-minute questionnaire, we would like to know:

Concerning the project entitled "Implementing the LLL algorithm in FLINT" developed in GSoC 2014.

1. Do you have a GitHub repository for the GSoC project? If so, could you provide us with the link to the project?

2. Have you continued committing code or opening issues to the GSoC project after GSoC? (Yes / No) If so, code, issues or both?

3. Have you continued committing code or opening issues to other OSS projects after GSoC? (Yes / No) If so, code, issues or both?

4. Could we use aggregate data from your participation in GSoC and other OSS projects in our research?

The following link contains a sample of our work and how we would use your data:
https://ieeexplore.ieee.org/document/8094410/

Regards,

Jefferson

**Comment by fandango96** [comment]
Hi Jefferson,

1. I was a participant twice (2014, 2015): The repos are https://github.com/fandango-/flint2 and https://github.com/fandango-/fricas

2. No. However, both projects were merged and no issues requiring code changes have come up so far.

3. Yes, both

4. Yes

Thanks,
Abhinav

**Comment by j3ffsilva** [comment]
Hello Abhinav,

Thanks for participating in the survey.

Best,

Jefferson

Em dom, 9 de set de 2018 às 15:46, Abhinav Baid <notifications@github.com>
escreveu:
